# Generated by Django 5.1.4 on 2024-12-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_edit', '0003_splitequallyvideoupload_splitvideoupload_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SplitEquallyVideoUpload',
        ),
    ]
