# Generated by Django 5.1.4 on 2024-12-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_edit', '0004_delete_splitequallyvideoupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitEquallyVideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('split_equally_video_file', models.FileField(upload_to='split_equally_videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
