# Generated by Django 5.1.4 on 2024-12-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_edit', '0005_splitequallyvideoupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='videos_for_audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
