# Generated by Django 5.1.4 on 2025-01-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_edit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractAudio',
        ),
    ]
